// About section (Settings) and the sidebar version chip: real runtime
// version, curated external links, copyable diagnostics, and third-party
// attribution (js/licenses.data.js, regenerated by
// scripts/generate_attributions.py).

(function () {
  const versionEl = document.getElementById('about-version');
  const versionChip = document.getElementById('app-version-chip');
  const buildLine = document.getElementById('about-build-line');
  const copyBtn = document.getElementById('about-copy-diagnostics');
  const licensesEl = document.getElementById('about-licenses');
  const crateList = document.getElementById('about-crate-list');
  const linkButtons = Array.from(
    document.querySelectorAll('#about-group .btn-small[id^="about-link-"], .about-model-link')
  );

  async function loadInfo() {
    try {
      const info = await invoke('about_info');
      const v = `v${info.version}${info.debug_build ? ' (dev)' : ''}`;
      versionEl.textContent = v;
      versionChip.textContent = v;
      versionChip.hidden = false;
      buildLine.textContent =
        `${info.os} ${info.arch} · GPU: ${info.gpu_backend} · Tauri ${info.tauri_version}`;
    } catch (err) {
      console.error('Failed to load about info:', err);
    }
  }

  function onLinkClick(event) {
    const btn = event.currentTarget;
    // "about-link-repo" -> "repo"; model buttons carry data-link directly.
    const id = btn.dataset.link || btn.id.replace('about-link-', '');
    invoke('open_about_link', { id }).catch((err) => {
      showToast(`Could not open link: ${err}`, 'error');
    });
  }

  async function onCopyDiagnostics() {
    try {
      const report = await invoke('diagnostics_report');
      await navigator.clipboard.writeText(report);
      showToast('Diagnostics copied to clipboard', 'success');
    } catch (err) {
      showToast(`Could not copy diagnostics: ${err}`, 'error');
    }
  }

  // Render lazily on first expand: ~770 rows have no business in the initial
  // layout pass.
  let cratesRendered = false;
  function renderCrates() {
    if (cratesRendered) return;
    cratesRendered = true;
    const data = window.LICENSES_DATA;
    if (!data || !Array.isArray(data.crates) || !data.crates.length) {
      crateList.textContent = 'Attribution data was not bundled with this build.';
      return;
    }
    const frag = document.createDocumentFragment();
    for (const crate of data.crates) {
      const row = document.createElement('div');
      row.className = 'about-crate';
      const name = document.createElement('span');
      name.className = 'about-crate__name';
      name.textContent = `${crate.name} ${crate.version}`;
      const license = document.createElement('span');
      license.className = 'about-crate__license';
      license.textContent = crate.license;
      row.append(name, license);
      frag.appendChild(row);
    }
    crateList.replaceChildren(frag);
    const heading = document.getElementById('about-crate-heading');
    if (heading) heading.textContent = `Rust libraries (${data.crates.length})`;
  }

  function onToggle() {
    if (licensesEl.open) renderCrates();
  }

  for (const btn of linkButtons) btn.addEventListener('click', onLinkClick);
  copyBtn.addEventListener('click', onCopyDiagnostics);
  licensesEl.addEventListener('toggle', onToggle);
  loadInfo();

  window.addEventListener('beforeunload', () => {
    for (const btn of linkButtons) btn.removeEventListener('click', onLinkClick);
    copyBtn.removeEventListener('click', onCopyDiagnostics);
    licensesEl.removeEventListener('toggle', onToggle);
  });
})();
