#!/usr/bin/env python3
"""Regenerate the third-party attribution data shown in the app's About
section (crates/murmur-app/frontend/js/licenses.data.js) from `cargo
metadata`, so the list tracks the real dependency tree instead of rotting.

Run with `uv run scripts/generate_attributions.py` from the repo root after
dependency changes. Includes every non-workspace package cargo resolves for
the workspace with all shipping features; slight over-inclusion (build/dev
deps) is preferred to under-attribution.
"""

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates" / "murmur-app" / "frontend" / "js" / "licenses.data.js"


def main() -> int:
    meta = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--features", "full"],
            cwd=ROOT,
        )
    )
    workspace = set(meta["workspace_members"])
    crates = []
    for pkg in meta["packages"]:
        if pkg["id"] in workspace:
            continue
        crates.append(
            {
                "name": pkg["name"],
                "version": pkg["version"],
                "license": pkg.get("license") or "unknown",
                "repository": pkg.get("repository") or "",
            }
        )
    crates.sort(key=lambda c: (c["name"], c["version"]))
    body = json.dumps({"crates": crates}, indent=None, separators=(",", ":"))
    OUT.write_text(
        "// Generated by scripts/generate_attributions.py; do not edit by hand.\n"
        f"window.LICENSES_DATA = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(crates)} crates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
